shenyu:
  register:
    registerType: http
    serverLists: ${SHENYU_REGISTER_SERVERLISTS}
    props:
      username: ${SHENYU_REGISTER_PROPS_USERNAME}
      password: ${SHENYU_REGISTER_PROPS_PASSWORD}
  client:
    dubbo:
      props:
        contextPath: /crm
        appName: union_cash

#Dubbo配置
dubbo:
  application:
    name: test-dubbo-service
    register-mode: interface
    qos-enable: false
  registry:
    use-as-config-center: true # 关闭dubbo的配置中心配置
    address: ${DOUBBO_REGISTRY_ADDRESS}
    username: ${DOUBBO_REGISTRY_USERNAME}
    password: ${DOUBBO_REGISTRY_ADDRESS}
    parameters:
      namespace:
      group:
  protocol:
    name: dubbo
    port: -1
  scan:
    base-packages: me.flyray.bsin.server.impl
  provider:
    validation: true
  consumer:
    check: false


# seata配置
seata:
  # 是否开启spring-boot自动装配
  enabled: true
  # 是否启用数据源 bean 的自动代理
  enable-auto-data-source-proxy: false
  # Seata 应用编号，默认为 ${spring.application.name}
  application-id: ${spring.application.name}
  # Seata 事务组编号，用于 TC 集群名
  tx-service-group: default_tx_group
  config:
    type: nacos
    nacos:
      server-addr: ${nacos.server-addr}
      group: SEATA_GROUP
      namespace: ${nacos.seata-namespace}
      data-id: seataServer.properties
      username: ${nacos.username}
      password: ${nacos.password}
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: ${nacos.server-addr}
      group: SEATA_GROUP
      namespace: ${nacos.seata-namespace}
      username: ${nacos.username}
      password: ${nacos.password}

#数据库配置
spring:
  application:
    # 应用名称
    name: test-dubbo-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/shenyu?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
    username: root
    password: 12345678
    #连接池配置
    druid:
      enable: true
      max-active: 200
      max-open-prepared-statements: 150
      max-wait: 6000
      min-evictable-idle-time-millis: 300000
      min-idle: 50
      pool-prepared-statements: false
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      validation-query: select 1